# fly.toml app configuration file generated for ee-dev on 2023-12-28T15:05:01+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512
